spring:
  redis:
    ################### redis 单机版 start ##########################
    host: 127.0.0.1
    password: ENC(TfsiXwZLxeC5ZZ3A+wFyfA+4YvmFaB/SOilpFR1u0zauBRx5N2FZ7wBjyFJ8POn/)
    port: 6379
    timeout: 6000
    database: 2
    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）,如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-idle: 8   # 连接池中的最大空闲连接 ，默认值也是8
        max-wait: 100 # # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        min-idle: 2    # 连接池中的最小空闲连接 ，默认值也是0
      shutdown-timeout: 100ms
      ################### redis 单机版 start ##########################